apiVersion: v1
kind: Pod
metadata: 
  name: alpine-pod
spec:
  containers:
    - image: alpine:3
      name: alpine-container
      ports:
        - containerPort: 80
          protocol: TCP
      command:
        - sleep
        - 1d    