---
apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
    - name: init-container-1
      image: alpine:3
      command:
        - sleep
        - 30s
      ports:
        - containerPort: 80
          protocol: TCP  
    - name: init-container-2
      image: alpine:3
      command:
        - sleep
        - 30s
      ports:
        - containerPort: 80
          protocol: TCP 
  containers:
    - name: nginx-container
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP
       