---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod1
  labels:
    app: nginx
    version: "1.23"
spec:
  containers:
    - name: nginx-container1
      image: nginx:1.23 
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod2
  labels:
    app: nginx 
    version: "1.26"
spec:
  containers:
    - name: nginx-container2
      image: nginx:1.23
      ports:
        - containerPort: 80
          protocol: TCP             
      