---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginxrs-pod
spec:
  minReadySeconds: 5
  replicas: 4
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginxrs-pod
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector: 
    app: nginx
  ports:
    - targetPort: 80
      port: 35000
      protocol: TCP  
      name: web