apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-pod
  labels: 
    environment: dev
spec:
  minReadySeconds: 5
  replicas: 6
  selector: 
    matchLabels: 
      environment: dev
  template:
    metadata: 
      name: rc-pod
    spec:
      containers:
        - image: alpine:3
          name: alpine-container
            