apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-alpine
spec:
  minReadySeconds: 5
  replicas: 6
  selector:  
      environment: dev
  template:
    metadata: 
      name: rc-alpine-pod
      labels: 
        environment: dev
        sprint: "1"
    spec:
      containers:
        - image: alpine:3
          name: alpine-container
            