apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: rs-pod
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      name: rs-pod
      labels:
        app: nginx
        ver: 1.23
  spec:
    containers:
      - name: nginx-container
        image: nginx:1.23
        ports:
          - containerPort: 80
            protocol: TCP
                  