---
apiVersion: v1
kind: Pod
metadata:
  name: restart-pod
spec:
  restartPolicy: Never
  containers:
    - image: alpine:3
      name: restart-container
      ports:
        - containerPort: 80
          protocol: TCP
      command:
        - sleep
        - 2s    

---
apiVersion: v1
kind: Pod
metadata:
  name: restartalways-pod
spec:
  restartPolicy: Always
  containers:
    - image: alpine:3
      name: restart-default
      ports:
        - containerPort: 80
          protocol: TCP
      command:
        - sleep
        - 2s  
