---
apiVersion: v1
kind: Pod
metadata: 
  name: simple-pod
spec: 
  containers:
    - image: nginx:1.23
      name: ngnix-container
      ports: 
        - containerPort: 80
          hostport: 3556
          protocol: TCP
     