---
apiVersion: v1
kind: Pod
metadata: 
  name: simple-pods2
spec:
  containers:
    - image: nginx:1.23
      name: ngnix-container
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins-container
      ports:
        - containerPort: 8080
          protocol: TCP      
     